name: Deploy

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH directory
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Install NVM, Node, and Yarn
        run: |
          # Install NVM
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          # Source NVM to make it available in this shell
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          # Install the specific version of Node.js (same as on your server)
          nvm install v20.9.0
          # Install Yarn globally
          npm install -g yarn
          # Verify that Yarn is available
          yarn --version

      - name: Add Server to Known Hosts
        run: ssh-keyscan -H kitech.rw >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.YEAN_WEB_SECRET }}
        run: |
          # Save the private key for SSH authentication
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # SSH into the server and make sure to source NVM before running any commands
            ssh -o StrictHostKeyChecking=no -p 22 root@46.101.129.106 << 'EOF'

            # Ensure NVM is sourced
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Verify that nvm and yarn are available
            nvm --version
            yarn --version

            # Determine the branch based on the event type
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              BRANCH_NAME="${{ github.event.pull_request.head.ref }}"  # Source branch for pull requests
            else
              BRANCH_NAME="${{ github.event.ref }}"  # Target branch for pushes
              BRANCH_NAME=${BRANCH_NAME#refs/heads/}  # Remove refs/heads/ prefix
            fi

            # Determine the project directory based on the branch
            if [ "$BRANCH_NAME" == "main" ]; then
              PROJECT_DIR="/srv/www/yean-web"
              SCRIPT_PATH="/scripts/build.sh"
            else
              PROJECT_DIR="/srv/www/dev/yean-web"
              SCRIPT_PATH="/scripts/builddev.sh"
            fi

            # Navigate to the appropriate project directory
            cd "$PROJECT_DIR"
            
            # Pull the latest changes
            git pull origin "$BRANCH_NAME"

            # Run the script and pass the branch name as an argument 
            bash "$SCRIPT_PATH" "$BRANCH_NAME"
          EOF
