name: Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH directory
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Add Server to Known Hosts
        run: ssh-keyscan -H kitech.rw >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.YEAN_WEB_SECRET }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Determine which script to run based on the branch
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            SCRIPT_PATH="~/build.sh"
          else
            SCRIPT_PATH="~/builddev.sh"
          fi
          ssh -o StrictHostKeyChecking=no -p 22 root@46.101.129.106 "$SCRIPT_PATH"